##===- lib/TLS/Makefile ------------------------------------*- Makefile -*-===##
#
#                     Sambamba
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
ifneq (,$(wildcard $(LEVEL)/Makefile.common))
	LIBRARYNAME = TLS
	NO_INSTALL = 1
	include $(LEVEL)/Makefile.common
else
	include Makefile.standalone
endif
